[rootfs] remove user superuser it's not getting setup
bitnami/bitnami-docker-dokuwiki pull request #87
Opened 2020-11-02 19:02 UTC by Nokius

**Description of the change**

remove a not rolled out user called superuser
**Benefits**

clean up the code
**Possible drawbacks**

non.
**Applicable issues**

-
**Additional information**

See PR #86 which showed the issue at the first place.

2020-11-02 19:04 UTC, Nokius commented
There is one more [file ](https://github.com/bitnami/bitnami-docker-dokuwiki/blob/master/20200729/debian-10/rootfs/opt/bitnami/scripts/libdokuwiki.sh#L100)calling a superuser, I'm not famillier with the setup of dokuwiki but I assume it's a switch to create via an api a superuser. There is no need to touch anything.

2020-11-02 19:05 UTC, Nokius commented on 20200729/debian-10/rootfs/opt/bitnami/scripts/dokuwiki-env.sh
> -    DOKUWIKI_USERNAME
even now just one user was created no need to have two exported.

2020-11-02 19:05 UTC, Nokius commented on 20200729/debian-10/rootfs/opt/bitnami/scripts/dokuwiki-env.sh
> -export DOKUWIKI_USERNAME="${DOKUWIKI_USERNAME:-superuser}"
the user is not rolled out -> code cleanup

2020-11-03 11:44 UTC, alemorcuq requested changes

2020-11-03 11:44 UTC, alemorcuq commented on 20200729/debian-10/rootfs/opt/bitnami/scripts/dokuwiki-env.sh
> -export DOKUWIKI_USERNAME="${DOKUWIKI_USERNAME:-superuser}"
Hi, @Nokius. Thanks for this. Do you mind removing `user` instead of `superuser`? The README mentions that `superuser` is the default username, so it should be the expected one.

2020-11-03 18:02 UTC, Nokius commented on 20200729/debian-10/rootfs/opt/bitnami/scripts/dokuwiki-env.sh
> -export DOKUWIKI_USERNAME="${DOKUWIKI_USERNAME:-superuser}"
I changed the it now user is not getting rolled out anymore.

2020-11-04 08:02 UTC, alemorcuq approved these changes
Thanks!

2020-11-04 09:21 UTC, merged